version: '3'

services:
  api:
    container_name: api
    image: repfabriccontactpoc-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always   

volumes:
  mysqldb: